/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import java.awt.BorderLayout;
import java.awt.Color;
import static java.awt.Component.BOTTOM_ALIGNMENT;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JViewport;

/**
 *
 * @author QCU
 */
public class PendingReportItem extends javax.swing.JFrame {

    /**
     * Creates new form PendingReportItem
     */
    public PendingReportItem() {
        initComponents();
        displayItemCards();
        r.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // 🔁 Refresh your table or panel here
                displayItemCards(); // or your refresh method

            }
        });
    }
    user.ItemReport r = new user.ItemReport();
    int itemId;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));
        jPanel1.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(50, 50));

        cardPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        cardPanel.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("<html><body style='margin-left: 10px;'><a href='#'> Report Item</a></body></html>");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(cardPanel);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(178, 70, 2230, 630);

        jPanel7.setBackground(new java.awt.Color(0, 39, 117));
        jPanel7.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qcu-logo.png"))); // NOI18N

        jLabel22.setBackground(new java.awt.Color(0, 51, 153));
        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Lost and Found");

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(982, 982, 982)
                .addComponent(jLabel3)
                .addContainerGap(1038, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 0, 2310, 70);

        jPanel6.setBackground(new java.awt.Color(0, 51, 153));
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(82, 700));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 51, 255));
        jPanel8.setMinimumSize(new java.awt.Dimension(32, 20));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 105, -1, 35));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("  Found Item ");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, 108, 35));

        jLabel19.setBackground(new java.awt.Color(153, 153, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText(" Claim Item");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setPreferredSize(new java.awt.Dimension(35, 20));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 166, 96, 35));

        jPanel17.setBackground(new java.awt.Color(102, 102, 255));
        jPanel17.setOpaque(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 100, -1, -1));

        jPanel18.setBackground(new java.awt.Color(102, 102, 255));
        jPanel18.setOpaque(false);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 482, -1, -1));

        jLabel27.setBackground(new java.awt.Color(153, 153, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel27.setText("Pending Report");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.setPreferredSize(new java.awt.Dimension(35, 20));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 219, 127, -1));

        jPanel9.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, 40));

        jLabel24.setBackground(new java.awt.Color(0, 51, 153));
        jLabel24.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("QCU");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 21, -1, 40));

        jLabel20.setBackground(new java.awt.Color(153, 153, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Profile");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setPreferredSize(new java.awt.Dimension(35, 20));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 51, -1));

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 70, 180, 650);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

//        r.setVisible(true);
//        r.setDefaultCloseOperation(user.ItemReport.DISPOSE_ON_CLOSE); // ✅ Only closes this window
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        if (user.Session.currentUsername != null && user.Session.userId != null){
            user.Session.currentUsername = null;
            user.Session.userId = null;
            user.Session.userSchoolId = null;
            JOptionPane.showMessageDialog(this, "Logout Successfully");
            new userAuth.Login().setVisible(true);
            this.dispose();
        } else {
            new userAuth.Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        new ItemDisplay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
       Profile windows = new Profile();
       windows.show();
       dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        new ClaimItem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        new PendingReportItem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    public void displayItemCards() {
        cardPanel.removeAll();
        String query = "SELECT ir.*, ct.claimId, ct.whoclaim, ct.timestamp AS claim_timestamp FROM itemreport ir JOIN claims_tbl ct ON ct.claimId = ir.id WHERE (ir.reportId = ? AND ir.studentNum = ?) OR (ct.whoclaim = ? AND ct.studentNumber = ?)";
        cardPanel.setLayout(new Table.wrapLayout(FlowLayout.LEFT, 15, 15));
        cardPanel = new JPanel(cardPanel.getLayout()) {
            @Override
            public Dimension getPreferredSize() {
                if (getParent() instanceof JViewport) {
                    int width = ((JViewport) getParent()).getWidth();
                    setSize(width, 0);
                }
                return super.getPreferredSize();
            }
        };

        jScrollPane1.setViewportView(cardPanel);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        if (Session.userId != null) {
            try (Connection con = DBConnection.DataBase.getConnection(); PreparedStatement ps = con.prepareStatement(query)) {

                ps.setInt(1, Session.userId);
                ps.setString(2, Session.userSchoolId);
                ps.setInt(3, Session.userId);
                ps.setString(4, Session.userSchoolId);

                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    JPanel card = createCard(rs);
                    cardPanel.add(card);
                }

                jScrollPane1.getViewport().addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentResized(ComponentEvent e) {
                        cardPanel.revalidate();
                        cardPanel.repaint();
                    }
                });
                cardPanel.setBackground(Color.white);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error loading items: " + e.getMessage());
            }
        } else {
            JLabel statusLbl = new JLabel("No Pending");
            statusLbl.setFont(new Font("Segoe UI Variable", Font.BOLD, 20));
            cardPanel.add(statusLbl);
        }

    }

    private JPanel createCard(ResultSet rs) throws Exception {
        ItemDisplay id = new ItemDisplay();
        String status1 = rs.getString("status");
         Timestamp createdAt = rs.getTimestamp("claim_timestamp");
        String timeAgo = id.getTimeAgo(createdAt);
        int whoclaim = rs.getInt("whoclaim");
        
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBackground(Color.WHITE);
        card.setPreferredSize(new Dimension(270, 470));

        // Header panel
        JPanel headPanel = new JPanel();
        headPanel.setLayout(new BoxLayout(headPanel, BoxLayout.X_AXIS));
        headPanel.setBorder(BorderFactory.createEmptyBorder(0, 2, 2, 0));
        headPanel.setBackground(Color.white);
        headPanel.setMaximumSize(new Dimension(270, 20));

        // Components
        JLabel stat = new JLabel();
        JLabel time = new JLabel(timeAgo);

        if ((status1.equalsIgnoreCase("Claimed") 
            || status1.equalsIgnoreCase("Claim Pending") 
            || status1.equalsIgnoreCase("Claim Request") 
            || status1.equalsIgnoreCase("Claim Approved")) 
            && whoclaim == (int) Session.userId) {

            stat.setText("Claim");
        } else {
            stat.setText("Report");
        }

        stat.setFont(new Font("Segoe UI Variable", Font.PLAIN, 14));
        time.setFont(new Font("Segoe UI Semilight", Font.PLAIN, 12));
        time.setForeground(Color.gray);

        // New: Add a flexible space between stat and time
        headPanel.add(stat);
        headPanel.add(Box.createHorizontalGlue()); // pushes time to the right
        headPanel.add(time);

        card.add(headPanel);
        
        JPanel status = new JPanel();
        JLabel statusLbl = new JLabel(status1);
        statusLbl.setFont(new Font("Segoe UI Variable", Font.BOLD, 16));
        statusLbl.setForeground(Color.white);

        if (status1.equalsIgnoreCase("Pending")) {
            status.setBackground(new Color(255, 150, 0));
        } else if (status1.equalsIgnoreCase("Posted")) {
            status.setBackground(new Color(89, 146, 201));
        } else if (status1.equalsIgnoreCase("Claimed")) {
            status.setBackground(new Color(45, 226, 0));
        } else if (status1.equalsIgnoreCase("Claim Requested")) {
            status.setBackground(new Color(128, 0, 128));
        } else {
            status.setBackground(new Color(178, 190, 181));
        }
        status.add(Box.createRigidArea(new Dimension(0, 10)));
        status.add(statusLbl);
        status.add(Box.createRigidArea(new Dimension(0, 10)));
        // Image
        JLabel imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(JLabel.CENTER);
        imageLabel.setVerticalAlignment(JLabel.CENTER);

        byte[] imgBytes = rs.getBytes("imageAttach");
        if (imgBytes != null) {
            Image img = ImageIO.read(new ByteArrayInputStream(imgBytes));
            Image scaledImg = getScaledImage(img, 270, 225);
            imageLabel.setIcon(new ImageIcon(scaledImg));

        } else {
            imageLabel.setText("No Image");
        }

        // Wrap the imageLabel in a JPanel with padding
        JPanel imagePanel = new JPanel(new BorderLayout());
        imagePanel.add(imageLabel, BorderLayout.CENTER);
        imagePanel.setBackground(Color.WHITE);

        int width = 235;
        int height = 20;

        JPanel infos = new JPanel();
        infos.setBackground(Color.WHITE);
        Font font = new Font("Segoe UI Variable", Font.PLAIN, 14);

        itemId = rs.getInt("id");
        JLabel nameLabel = new JLabel(rs.getString("itemName"));
        nameLabel.setMinimumSize(new Dimension(width, (height + 10)));
        nameLabel.setPreferredSize(new Dimension(width, (height + 10)));
        nameLabel.setMaximumSize(new Dimension(width, (height + 10)));
        nameLabel.setFont(new Font("Segoe UI Variable", Font.BOLD, 16));
        infos.add(nameLabel);
        infos.add(Box.createRigidArea(new Dimension(0, 20)));

        JLabel locationLabel = new JLabel("Location: " + rs.getString("location"));
        locationLabel.setMinimumSize(new Dimension(width, height));
        locationLabel.setPreferredSize(new Dimension(width, height));
        locationLabel.setMaximumSize(new Dimension(width, height));
        locationLabel.setFont(font);
        infos.add(locationLabel);
        infos.add(Box.createRigidArea(new Dimension(0, 2)));

        JLabel dateLabel = new JLabel("Date Lost: " + rs.getString("dateLost"));
        dateLabel.setMinimumSize(new Dimension(width, height));
        dateLabel.setPreferredSize(new Dimension(width, height));
        dateLabel.setMaximumSize(new Dimension(width, height));
        dateLabel.setFont(font);
        infos.add(dateLabel);
        infos.add(Box.createRigidArea(new Dimension(0, 2)));

        JLabel timeLabel = new JLabel("Time: " + rs.getString("timeLost"));
        timeLabel.setMinimumSize(new Dimension(width, height));
        timeLabel.setPreferredSize(new Dimension(width, height));
        timeLabel.setMaximumSize(new Dimension(width, height));
        timeLabel.setFont(font);
        infos.add(timeLabel);
        infos.add(Box.createRigidArea(new Dimension(0, 2)));

        String description = rs.getString("description");
        JLabel descLbl = new JLabel("<html><body style='width: 185px;'>Description: " + description + "</body></html>");
        descLbl.setFont(font);
        descLbl.setAlignmentX(LEFT_ALIGNMENT);
        descLbl.setAlignmentY(BOTTOM_ALIGNMENT);
        infos.add(descLbl);

        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(
                new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        contentPanel.setBackground(Color.white);
        contentPanel.add(status);
        contentPanel.add(imagePanel);
        contentPanel.add(Box.createRigidArea(new Dimension(0, 20)));
        infos.setPreferredSize(new Dimension(270, 250));
        contentPanel.add(infos);
        contentPanel.add(Box.createRigidArea(new Dimension(0, 15)));


        contentPanel.setPreferredSize(new Dimension(270, 450));
        contentPanel.setMaximumSize(new Dimension(270, 450));
        card.add(contentPanel);
        return card;

    }

    Image getScaledImage(Image srcImg, int width, int height) {
        BufferedImage resizedImg = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.drawImage(srcImg, 0, 0, width, height, null);
        g2.dispose();

        return resizedImg;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingReportItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingReportItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingReportItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingReportItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingReportItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
